wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0002
optimizer:
  desc: null
  value: torch.optim.adam.Adam
criterion:
  desc: null
  value: torch.nn.functional.cross_entropy
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701092703.761299
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 1
      - 5
      13: linux-x86_64
