wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: torch.optim.adam.Adam
criterion:
  desc: null
  value: MSELoss()
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701145841.160949
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
